# Site settings
url: "http://cb.platan.us" # the base hostname & protocol for your site

safe: false

paginate:             10

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

tag_page_layout: tags
tag_page_dir: tags

# Fetch data settings
data_fetch_resources:
  - url: http://platan.us/team.json?filter=all
    name: team
    item_name_key: github
exclude:
  - _data

# Jekyll compose
post_type: md

info:
  title: Codigo Banana
  subtitle: El blog de Platanus
  logo:         platanus-gravatar.png

  # cover_image:  bananas-background.jpg
  # cover_image_caption: "Short North, Columbus, OH. Photo: Pineapple XVI"

  twitter:      _platanus
  github:       platanus

  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id: 'UA-58887856-1'

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  codigobanana

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false
    reddit:     false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
